baseURL: 'https://aminalaee.dev'
title: Amin Alaee
theme: PaperMod
defaultContentLanguage: en
enableRobotsTXT: true
googleAnalytics: G-MV427T1Z9X

minify:
  disableXML: true
  minifyOutput: true

outputs:
  home:
    - HTML
    - RSS
    - JSON

params:
  defaultTheme: light
  env: production
  displayFullLangName: true
  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true

  homeInfoParams:
    Title: Amin Alaee
    Content: |
      I'm a software developer and open-source enthusiast.

      Feel free to  check my projects on GitHub and get in touch with me.

  socialIcons:
    - name: github
      url: 'https://github.com/aminalaee'
    - name: twitter
      url: 'https://twitter.com/aminalaee'
    - name: email
      url: 'mailto:mohammadamin.alaee@gmail.com'

menu:
  main:
    - identifier: archives
      name: Archives
      url: /archives/
      weight: 10
